site_name: Plexus Developer
site_description: Plexus Developer Portal
site_url: https://developer.plexus.co
copyright: Copyright &copy; Plexus

nav:
  - 'index.md'

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - content.code.annotate
    - toc.integrate
  logo: images/logo.svg
  favicon: images/favicon.png
  palette:
    - scheme: plexus
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Open Sans

# Strict mode, exit on warning
strict: true

# Hide edit button
edit_uri: ''

markdown_extensions:
  # Code highlighting
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets

  - admonition
  - pymdownx.details

  - pymdownx.tabbed:
      alternate_style: true

  - toc:
      permalink: true

extra:
  generator: false

extra_css:
  - stylesheets/colors.css
  - stylesheets/scheme.css
  - stylesheets/admonition.css
  - stylesheets/table.css
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - javascripts/tablesort.js
