site_name: Plexus Developer
site_description: Plexus Developer Portal
site_url: https://developer.plexus.co

theme:
  name: material
  features:
    - navigation.instant
  favicon: images/favicon.png
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

copyright: Copyright &copy; Plexus

# Strict mode, exit on warning
strict: true

# Hide edit button
edit_uri: ''

markdown_extensions:
  # Code highlighting
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets

  - admonition
  - toc:
      permalink: true

extra:
  generator: false

extra_css:
  - stylesheets/extra.css
extra_javascript:
- https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
- javascripts/tablesort.js